import type { UserRole } from "@/contracts/auth";

export const PERMISSIONS = [
  "patient.read",
  "patient.vitals.read",
  "patient.vitals.write",
  "patient.update.write",
  "ward.read",
  "ward.manage",
  "organ.match.read",
  "organ.waitlist.read",
  "prescription.create",
  "prescription.read",
  "prescription.dispense",
  "pharmacy.inventory.read",
  "pharmacy.inventory.manage",
  "blood.inventory.read",
  "blood.inventory.manage",
  "blood.donor.read",
  "blood.sos.create",
  "blood.map.read",
  "billing.read",
  "billing.manage",
  "insurance.read",
  "insurance.manage",
  "discharge.read",
  "discharge.manage",
  "notification.read",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  DOCTOR: [
    "patient.read",
    "patient.vitals.read",
    "patient.vitals.write",
    "patient.update.write",
    "ward.read",
    "organ.match.read",
    "organ.waitlist.read",
    "prescription.read",
    "prescription.create",
    "notification.read",
  ],
  NURSE: [
    "patient.read",
    "patient.vitals.read",
    "patient.vitals.write",
    "patient.update.write",
    "ward.read",
    "ward.manage",
    "prescription.read",
    "notification.read",
  ],
  BLOOD_BANK_COORDINATOR: [
    "blood.inventory.read",
    "blood.inventory.manage",
    "blood.donor.read",
    "blood.sos.create",
    "blood.map.read",
    "organ.match.read",
    "notification.read",
  ],
  PHARMACIST: [
    "prescription.read",
    "prescription.dispense",
    "pharmacy.inventory.read",
    "pharmacy.inventory.manage",
    "notification.read",
  ],
  BILLING_OFFICER: [
    "patient.read",
    "billing.read",
    "billing.manage",
    "insurance.read",
    "insurance.manage",
    "discharge.read",
    "discharge.manage",
    "notification.read",
  ],
  PATIENT: [
    "patient.read",
    "prescription.read",
    "billing.read",
    "insurance.read",
    "discharge.read",
    "notification.read",
  ],
  FAMILY_ATTENDANT: [
    "patient.read",
    "discharge.read",
    "notification.read",
  ],
};
