"use client";

import { useDischarge, useDownloadDischargePdf } from "../hooks/use-billing";
import { StatusBadge } from "@/components/data-display/status-badge";
import { formatDate } from "@/lib/utils/date";
import { Button } from "@/components/ui/button";
import { DownloadCloud, CheckCircle, FileText } from "lucide-react";
import { useState } from "react";
import { Alert } from "@/components/feedback/alert";
import { EmptyState } from "@/components/feedback/empty-state";
import { LoadingState } from "@/components/feedback/loading-state";

export function DischargeSummaryView({ patientId }: { patientId: string }) {
  const { data: discharges, isLoading } = useDischarge(patientId);
  const downloadPdf = useDownloadDischargePdf();
  const [downloadError, setDownloadError] = useState<string | null>(null);

  if (isLoading) return <LoadingState label="Loading discharge summary..." />;
  if (!discharges || discharges.length === 0) {
    return (
      <EmptyState
        icon={FileText}
        title="No discharge summary found"
        description="Finalized discharge instructions and follow-up details will appear here when they are available."
      />
    );
  }

  const discharge = discharges[0]; // Assuming one active discharge summary per patient context

  const handleDownload = async () => {
    setDownloadError(null);
    try {
      const blob = await downloadPdf.mutateAsync(patientId);
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `caregrid-discharge-${patientId}.pdf`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : "Failed to download PDF.";
      setDownloadError(message);
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-6">
        <div>
          <h2 className="text-2xl font-semibold tracking-tight">Discharge Summary</h2>
          <p className="text-muted-foreground text-sm mt-1">Patient: {discharge.patientId}</p>
        </div>
        <div className="flex items-center gap-3">
          <StatusBadge status={discharge.status === "FINALIZED" ? "APPROVED" : "PENDING"} />
          <Button 
            onClick={handleDownload} 
            disabled={downloadPdf.isPending}
            variant="default"
          >
            <DownloadCloud className="h-4 w-4 mr-2" />
            {downloadPdf.isPending ? "Downloading..." : "Download PDF"}
          </Button>
        </div>
      </div>

      {downloadError && (
        <Alert tone="critical" title="Error">
          {downloadError}
        </Alert>
      )}

      <div className="grid gap-6">
        {/* Stay Information Section */}
        <section className="rounded-lg border border-cyan-100/80 bg-gradient-to-br from-white via-cyan-50/50 to-emerald-50/40 p-6 text-card-foreground shadow-sm">
          <div className="flex items-center gap-2 mb-4 border-b pb-2">
            <CheckCircle className="h-5 w-5 text-emerald-600" />
            <h3 className="text-lg font-semibold">Stay Information</h3>
          </div>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
            <div>
              <p className="text-sm text-muted-foreground">Admission ID</p>
              <p className="font-medium">{discharge.admissionId}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Generated By</p>
              <p className="font-medium">{discharge.generatedByUserId}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Generated At</p>
              <p className="font-medium">{formatDate(discharge.generatedAt)}</p>
            </div>
          </div>
          <div>
            <h4 className="text-sm font-semibold text-muted-foreground mb-1">Clinical Summary</h4>
            <p className="text-sm leading-relaxed whitespace-pre-wrap">{discharge.staySummary}</p>
          </div>
        </section>

        {/* Lab Results Section */}
        <section className="rounded-lg border border-cyan-100/80 bg-gradient-to-br from-white via-sky-50/50 to-cyan-50/40 p-6 text-card-foreground shadow-sm">
          <div className="flex items-center gap-2 mb-4 border-b pb-2">
            <CheckCircle className="h-5 w-5 text-emerald-600" />
            <h3 className="text-lg font-semibold">Lab Results</h3>
          </div>
          {discharge.labResults ? (
            <p className="text-sm leading-relaxed whitespace-pre-wrap">{discharge.labResults}</p>
          ) : (
            <p className="text-sm text-muted-foreground italic">No lab results recorded.</p>
          )}
        </section>

        {/* Post-Discharge Medication Schedule */}
        <section className="rounded-lg border border-cyan-100/80 bg-gradient-to-br from-white via-emerald-50/50 to-cyan-50/40 p-6 text-card-foreground shadow-sm">
          <div className="flex items-center gap-2 mb-4 border-b pb-2">
            <CheckCircle className="h-5 w-5 text-emerald-600" />
            <h3 className="text-lg font-semibold">Post-Discharge Medication</h3>
          </div>
          {discharge.medicationSchedule ? (
            <p className="text-sm leading-relaxed whitespace-pre-wrap">{discharge.medicationSchedule}</p>
          ) : (
            <p className="text-sm text-muted-foreground italic">No medications prescribed for discharge.</p>
          )}
        </section>
      </div>
    </div>
  );
}
